Unets:
  Unet1:
    dim: 512
    image_embed_dim: 512
    text_embed_dim: 512
    cond_dim: 512
    channels: 3
    dim_mults: [1, 2, 3, 4] 
    cond_on_text_encodings: True
  
  Unet2:
    dim: 320
    image_embed_dim: 512
    text_embed_dim: 512
    cond_dim: 320
    channels: 3
    dim_mults: [1, 2, 3, 4] 
  
  Unet3:
    dim: 192
    image_embed_dim: 512
    text_embed_dim: 512
    cond_dim: 192
    channels: 3
    dim_mults: [1,1,2,2,4,4]

Decoder:
  image_sizes: [64, 256, 1024]
  timesteps: 1000
  image_cond_drop_prob: 0.1
  text_cond_drop_prob: 0.5
  condition_on_text_encodings: True
  # loss
  loss_type: 'l1'
  # diff
  beta_schedule: 'cosine'
  predict_x_start: False
  predict_x_start_for_latent_diffusion: False # not to latent now
  lowres_downsample_first: True
  # blur
  blur_sigma: 0.1
  blur_kernel_size: 3
  clip_denoised: True
  clip_x_start: True